#
# Copyright 2024 Copyright 2022 Aiven Oy and
# bigquery-connector-for-apache-kafka project contributors
#
# This software contains code derived from the Confluent BigQuery
# Kafka Connector, Copyright Confluent, Inc, which in turn
# contains code derived from the WePay BigQuery Kafka Connector,
# Copyright WePay, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# The workflow to create PRs with release commits.
name: Create changelog PR
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version '0.1.2' (without 'v')"
        required: true
      snapshot_version:
        description: "Snapshot version '0.2.0-SNAPSHOT' (without 'v')"
        required: true
      previous_release_version:
        description: "Previous release version '0.1.1' (without 'v')"
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create_changelog_pr:
    name: Create release PR (job)
    runs-on: ubuntu-latest
    steps:
      - name: Check versions
        run: |
          echo "Checking release version..."
          if echo ${{ github.event.inputs.release_version }} | '^[0-9]\+$' > /dev/null; then
            echo "Release version is invalid"
            exit 1
          fi

          echo "Checking snapshot version..."
          if echo ${{ github.event.inputs.snapshot_version }} | grep --invert-match '^[0-9]\+-SNAPSHOT$' > /dev/null; then
            echo "Snapshot version is invalid"
            exit 1
          fi
          
          echo "Checking previous release version..."
          if echo ${{ github.event.inputs.previous_release_version }} | '^[0-9]\+$' > /dev/null; then
            echo "Release version is invalid"
            exit 1
          fi

      - name: Checkout main
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Create changelog from v${{ github.event.inputs.previous_release_version }} to v${{ github.event.inputs.release_version }}
        run: |
          startTag=v${{ github.event.inputs.previous_release_version }};
          # v${{ github.event.inputs.release_version }};
          endTag=HEAD; 
          start=`git rev-parse ${startTag}`;
          end=`git rev-parse ${endTag}`;
          commits=${start}...${end};
          echo '## '${endTag} > /tmp/proposed_changelog.txt;
          echo '### What is changed' >> /tmp/proposed_changelog.txt;
          echo ' ' >> /tmp/proposed_changelog.txt;
          git log --format=' - %s'  ${commits} >> /tmp/proposed_changelog.txt;
          echo ' ' >> /tmp/proposed_changelog.txt;
          echo ' ' >> /tmp/proposed_changelog.txt;
          echo '### Co-authored by' >> /tmp/proposed_changelog.txt;
          echo ' ' >> /tmp/proposed_changelog.txt;
          git log --format=' - %an'  ${commits} | sort -u  >> /tmp/proposed_changelog.txt;
          echo ' ' >> /tmp/proposed_changelog.txt;
          echo ' ' >> /tmp/proposed_changelog.txt;
          echo '### Full Changelog' >> /tmp/proposed_changelog.txt;
          echo 'https://github.com/Aiven-Open/aiven-commons/compare/'${startTag}'...'${endTag}  >> /tmp/proposed_changelog.txt;
          echo ' ' >> /tmp/proposed_changelog.txt
          touch CHANGE_LOG.md
          cat /tmp/proposed_changelog.txt CHANGE_LOG.md >> /tmp/CHANGE_LOG.md
          mv /tmp/CHANGE_LOG.md CHANGE_LOG.md
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: changelog-${{ github.event.inputs.release_version }}
          delete-branch: true
          draft: true
          title: Changelog for v${{ github.event.inputs.previous_release_version }} to v${{ github.event.inputs.release_version }}
          body: |
            Proposed changelog Changelog for v${{ github.event.inputs.previous_release_version }} to v${{ github.event.inputs.release_version }}
              
